name: Integration Tests

on:
  push:
    branches: [ main, feat/526440-api-tests ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Run Integration Tests (PR)
      if: github.event_name == 'pull_request' && github.head_ref != 'feat/526440-api-tests'
      run: npm run test:integration

    - name: Run Integration Tests with Reports
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feat/526440-api-tests')
      run: |
        npm run test:integration:setup
        npm run test:integration:start
        npm run test:integration:wait
        
        # Generate reports
        mkdir -p ./newman/reports
        docker compose -f docker-compose.integration-test.yml run --rm \
          -v ${PWD}/newman/reports:/etc/newman/reports \
          newman run /etc/newman/forms-manager-ci-mock.postman_collection.json \
          -e /etc/newman/forms-manager-ci-mock.postman_environment.json \
          -r cli,json,html \
          --reporter-json-export /etc/newman/reports/newman-summary.json \
          --reporter-html-export /etc/newman/reports/newman-report.html
        
        EXIT_CODE=$?
        npm run test:integration:stop
        exit $EXIT_CODE

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feat/526440-api-tests')
      with:
        name: integration-test-report
        path: ./newman/reports/newman-report.html
        if-no-files-found: warn
